### ISSUE TITLE
用Bert的时候shape对应不上

### ISSUE THREAD

**Issue by szj2ys** [StanleyLsx/text_classifier#11]
epoch:1/5
  0%|                                                                        | 0/100 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    train(data_manage, logger)
  File "/Users/a12345/Downloads/models5/text_classifier/engines/train.py", line 101, in train
    logits = model(X_train_batch, training=1)
  File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3735, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /Users/a12345/Downloads/models5/text_classifier/engines/models/bert.py:33 call  *
        outputs = self.dense(dropout_outputs)
    /Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:982 __call__  **
        self._maybe_build(inputs)
    /Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:2643 _maybe_build
        self.build(input_shapes)  # pylint:disable=not-callable
    /Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py:1178 build
        trainable=True)
    /Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:614 add_weight
        caching_device=caching_device)
    /Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py:731 _add_variable_with_custom_getter
        name=name, shape=shape)
    /Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py:798 _preload_simple_restoration
        checkpoint_position=checkpoint_position, shape=shape)
    /Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py:75 __init__
        self.wrapped_value.set_shape(shape)
    /Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1209 set_shape
        (self.shape, shape))

    ValueError: Tensor's shape (192, 10) is not compatible with supplied shape [768, 10]

WARNING:tensorflow:Unresolved object in checkpoint: (root).model.embedding
WARNING:tensorflow:Unresolved object in ch

**Comment by stanleylsx** [comment]
> epoch:1/5 0%| | 0/100 [00:03<?, ?it/s] Traceback (most recent call last): File "main.py", line 27, in train(data_manage, logger) File "/Users/a12345/Downloads/models5/text_classifier/engines/train.py", line 101, in train logits = model(X_train_batch, training=1) File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in **call** outputs = call_fn(inputs, *args, **kwargs) File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in **call** result = self._call(*args, **kwds) File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call self._initialize(args, kwds, add_initializers_to=initializers) File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize *args, **kwds)) File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected graph_function, _, _ = self._maybe_define_function(args, kwargs) File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function graph_function = self._create_graph_function(args, kwargs) File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function capture_by_value=self._capture_by_value), File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func func_outputs = python_func(*func_args, **func_kwargs) File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn return weak_wrapped_fn().**wrapped**(*args, **kwds) File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3735, in bound_method_wrapper return wrapped_fn(*args, **kwargs) File "/Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper raise e.ag_error_metadata.to_exception(e) ValueError: in user code:
> 
> ```
> /Users/a12345/Downloads/models5/text_classifier/engines/models/bert.py:33 call  *
>     outputs = self.dense(dropout_outputs)
> /Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:982 __call__  **
>     self._maybe_build(inputs)
> /Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:2643 _maybe_build
>     self.build(input_shapes)  # pylint:disable=not-callable
> /Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py:1178 build
>     trainable=True)
> /Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:614 add_weight
>     caching_device=caching_device)
> /Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py:731 _add_variable_with_custom_getter
>     name=name, shape=shape)
> /Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py:798 _preload_simple_restoration
>     checkpoint_position=checkpoint_position, shape=shape)
> /Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py:75 __init__
>     self.wrapped_value.set_shape(shape)
> /Users/a12345/.local/share/virtualenvs/text_classifier-dT9bAj24/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1209 set_shape
>     (self.shape, shape))
> 
> ValueError: Tensor's shape (192, 10) is not compatible with supplied shape [768, 10]
> ```
> 
> WARNING:tensorflow:Unresolved object in checkpoint: (root).model.embedding WARNING:tensorflow:Unresolved object in ch

看看是不是加载了历史的模型？  
这个看起来是你没有修改checkpoint_name造成的？
