### ISSUE TITLE
训练error

### ISSUE THREAD

**Issue by uniqueLL** [StanleyLsx/text_classifier#13]
大佬你好，在训练的时候出现这个错误，我并没有改动什么，望解答
ValueError: Tensor's shape (67195, 300) is not compatible with supplied shape (82001, 300)

**Comment by stanleylsx** [comment]
> 大佬你好，在训练的时候出现这个错误，我并没有改动什么，望解答 ValueError: Tensor's shape (67195, 300) is not compatible with supplied shape (82001, 300)

见V5.0
