### ISSUE TITLE
这两个参数是什么意思？

### ISSUE THREAD

**Issue by zhanghaoxuan1999** [StanleyLsx/text_classifier#18]
attention_size
patient
您好，我在其他的项目论文中没有看到这两个参数的信息，想知道这两个参数是什么意思，以及它们的大小会产生什么影响？
在用bert等预训练模型中需要用这两个参数吗？

**Comment by stanleylsx** [comment]
> attention_size patient 您好，我在其他的项目论文中没有看到这两个参数的信息，想知道这两个参数是什么意思，以及它们的大小会产生什么影响？ 在用bert等预训练模型中需要用这两个参数吗？

attention_size是TextRNN里面的注意力矩阵的大小，不适用它的时候不用管；
patient是early_stop的参数，当patient次模型不会有进步时候自动停止训练。
