### ISSUE TITLE
请问 word-token2id 文件时怎么生成的？

### ISSUE THREAD

**Issue by jasonsun001** [StanleyLsx/text_classifier#21]
![image](https://user-images.githubusercontent.com/33573290/187775229-858c352a-0b04-4119-b5e3-dea60e037d85.png)

**Comment by StanleyLsx** [comment]
> ![image](https://user-images.githubusercontent.com/33573290/187775229-858c352a-0b04-4119-b5e3-dea60e037d85.png)

是自动根据你的预料自动生成的

**Comment by stanleylsx** [comment]
> ![image](https://user-images.githubusercontent.com/33573290/187775229-858c352a-0b04-4119-b5e3-dea60e037d85.png)

你填好数据集的目录后，程序自动读取，然后根据语料自动生成

**Comment by jasonsun001** [comment]
如果后期出现新的词呢，我觉得应该要可以追加。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月1日(周四) 晚上9:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [StanleyLsx/text_classifier_tf2] 请问 word-token2id 文件时怎么生成的？ (Issue #21)




  

  
你填好数据集的目录后，程序自动读取，然后根据语料自动生成
