### ISSUE TITLE
如果后期有新的语料，新的词汇进来，是不是应该要有追加功能，而不是直接覆盖原来的 token2id 文件？

### ISSUE THREAD

**Issue by jasonsun001** [StanleyLsx/text_classifier#22]
如果后期有新的语料，新的词汇进来，有追加单个词汇token2id 功能的功能吗，而不是直接覆盖原来的 token2id 文件？

**Comment by stanleylsx** [comment]
> 如果后期有新的语料，新的词汇进来，有追加单个词汇token2id 功能的功能吗，而不是直接覆盖原来的 token2id 文件？

暂时没有了，如果你使用预训练模型，不会走token2id这一套，所以不用考虑增加词表相关问题；
如果你是用textcnn这些传统的网络，网络里面的embedding层已经将词表固化了，新增语料要么就是直接用老词表出现UNK代替，要么就是全部重新生成词表再训练。
