### ISSUE TITLE
回复

### ISSUE THREAD

**Issue by jasonsun001** [StanleyLsx/text_classifier#24]
如果你是用textcnn这些传统的网络，网络里面的embedding层已经将词表固化了，新增语料要么就是直接用老词表出现UNK代替，要么就是全部重新生成词表再训练。
>>> 如果有这样一个场景，每周都会获得一些最新的语料：

                可以这样吗？把每周新增的语料中新出现的词加在老的词表（word2id）后面，id 也是跟着累加。然后加载上一次的训练好的模型，也就是基于上一次的预训练模型，继续训练，但是训练的是这周新获得的语料，而当中的新词已经追加到原来的词表后面了。
                这样子的话，我觉得不需要重新生成词表，同时，模型可以“持续地识别更多新词，持续地训练下去”。

**Comment by stanleylsx** [comment]
> 如果你是用textcnn这些传统的网络，网络里面的embedding层已经将词表固化了，新增语料要么就是直接用老词表出现UNK代替，要么就是全部重新生成词表再训练。
> 
> > > > 如果有这样一个场景，每周都会获得一些最新的语料：
> 
> ```
>             可以这样吗？把每周新增的语料中新出现的词加在老的词表（word2id）后面，id 也是跟着累加。然后加载上一次的训练好的模型，也就是基于上一次的预训练模型，继续训练，但是训练的是这周新获得的语料，而当中的新词已经追加到原来的词表后面了。
>             这样子的话，我觉得不需要重新生成词表，同时，模型可以“持续地识别更多新词，持续地训练下去”。
> ```


兄弟，我觉得你可能还要学习下预训练模型相关的知识，看一下Bert，然后尝试使用下https://huggingface.co/bert-base-chinese
一切你都会通的。

**Comment by stanleylsx** [comment]
> 如果你是用textcnn这些传统的网络，网络里面的embedding层已经将词表固化了，新增语料要么就是直接用老词表出现UNK代替，要么就是全部重新生成词表再训练。
> 
> > > > 如果有这样一个场景，每周都会获得一些最新的语料：
> 
> ```
>             可以这样吗？把每周新增的语料中新出现的词加在老的词表（word2id）后面，id 也是跟着累加。然后加载上一次的训练好的模型，也就是基于上一次的预训练模型，继续训练，但是训练的是这周新获得的语料，而当中的新词已经追加到原来的词表后面了。
>             这样子的话，我觉得不需要重新生成词表，同时，模型可以“持续地识别更多新词，持续地训练下去”。
> ```

你用预训练模型，是不用考虑我项目里面的word2id的，如果你有仔细读代码，一定能知道代码没有走到读取本地的词表。
新添加的语料，在预训练模型只需要拿新语料固定时间进行further fintune就可以了。
然后麻烦不要在开新的issue了 谢谢
